flackr/scroll-timeline

demo/view-timeline-css/index.html
With the scope of view-timelines now properly implemented in https://github.com/flackr/scroll-timeline/pull/83, this demo needs fixing because the target not find a scroll-subject to hook onto.
=> Fix view-timeline-css demo

demo/view-timeline-css/index.html, demo/view-timeline-css/with-delays-using-animation-time-range.html, src/proxy-animation.js, src/scroll-timeline-css-parser.js
**TL;DR**
Rename "animation-time-range" to "animation-range" because this is the latest spec (according to [this](https://github.com/flackr/scroll-timeline/issues/64#issuecomment-1544020128) comment).
**WHY**
At the moment polyfill implementation diverged from the latest spec.
That means we can't produce tutorials or educational materials that show use of the latest (accepted) spec because the polyfill itself is not up-to-date with the latest spec.
This PR brings the polyfill a little bit closer to the current version of the spec.
@bramus @flackr @kevers-google My apologies for poking you like this directly in this PR. I am not sure how else to draw attention to this 😀
=> Rename "animation-time-range" -> "animation-range" to match the accepted spec

src/intersection-based-offset.js, src/scroll-timeline-base.js, src/scroll-timeline-css-parser.js
The values `horizontal` and `vertical` are no longer valid as per recent spec change. They have been replaced by the values `x` and `y` respectively. This PR lands that rename, while also fixing a bug along the way.
With this PR applied, the demo at `/demo/parallax/` starts working correctly again upon switching the mode to either “Horizontal left to right” or “Horizontal right to left”.
=> Fix axis names

src/scroll-timeline-base.js, src/scroll-timeline-css-parser.js
This PR adds support for anonymous view timelines, which fixes #129.
Marking this PR as a draft as it currently only covers `view()` and `view(axis)` support. It does not cater for `view(inset)` nor `view(axis inset)` yet.
I am using separate code paths to keep the ScrollTimeline and ViewTimeline code separated, even though both are using the same logic and structure. An alternative approach could be to merge both code paths, but then it would need some trickery in `getAnonymousTimelineOptions` to differentiate between ScrollTimelines and ViewTimelines, so that it can return the correct `options` for each type. I thought of using a different prefix for the anonymous timeline name _(using `:st` and `:vt` instead of just `:t` to differentiate between both)_ but that felt a bit hacky.
=> Add anonymous view timeline support (`view()`)

src/scroll-timeline-css-parser.js
This `parseError` method is called in the CSS parser but is nowhere to be found. This PR fixes this.
The function is adapted from https://github.com/GoogleChromeLabs/container-query-polyfill/blob/faf2600f7cd7b16e500f40676dd1b144005bd186/src/engine.ts#L418, which formed the basis of the CSS Parser used in the scroll-timeline polyfill.
=> Add missing parseError function

src/scroll-timeline-css-parser.js
In JavaScript Strict Mode, all variables need to be declared. Fixes #119.
=> Declare `parts` variable before using it

src/proxy-animation.js
When no range information is passed in via the Animation’s `options`, demos such as the one in https://github.com/flackr/scroll-timeline/issues/119#issuecomment-1658247473 would throw an error: `TypeError: null is not an object (evaluating 'n.rangeName')`.
This PR makes sure that the default rangeOffset value is used when none is given.
=> Return the default rangeOffset when no value is given

src/scroll-timeline-base.js, src/scroll-timeline-css-parser.js, src/scroll-timeline-css.js
Some minor code cleanups but also two bigger ones:
- fce08c1a83f779794d5e15e0d7f1984fcb145379 Remove old `@scroll-timeline` parsing logic
- 453fdf4ed324bfe7d4769cc4557ff289635aabd4 Remove code that tries to extract the `animation-timeline` from the `animation` shorthand
=> Remove old/unused code

src/proxy-animation.js
Demo: https://codepen.io/bramus/pen/oNJxoOX/a1a2b578349faf9299bb18c778fe4cf3
In this demo, the `effect` – which uses a `ScrollTimeline` as its `timeline` – on an animation is being set.
When doing so, this error gets thrown:
```
ReferenceError: Can't find variable: details
```
This because that variable is not declared within that function:
https://github.com/flackr/scroll-timeline/blob/5fab1816ad4f13e2cef3cd27ce6b243027a4970f/src/proxy-animation.js#L851-L855
This PR fixes that.
=> Fix setting the effect

src/proxy-animation.js
Fixes #144. 
See https://github.com/flackr/scroll-timeline/issues/144#issuecomment-1697705355 and https://github.com/flackr/scroll-timeline/issues/144#issuecomment-1697942416 for details.
Here’s a before and after recording:
- Without Fix:
https://github.com/flackr/scroll-timeline/assets/213073/d0b49e0a-89e1-4330-94e9-b7a203c6d564
- With Fix:
https://github.com/flackr/scroll-timeline/assets/213073/00fa694d-87d7-4a79-ba63-d0b1dfdd6291
=> Correctly handle already finished ViewTransition animations upon load

src/scroll-timeline-base.js, src/scroll-timeline-css.js
This PR clear the `proxyAnimations` cache when the page gets unloaded [using the unload event](https://webkit.org/blog/516/webkit-page-cache-ii-the-unload-event/). By clearing that cache new `ProxyAnimation` instances get created when going back using the browsers’s history.
This is needed for Safari, whose BFCache doesn’t play nice with this polyfill. See https://github.com/flackr/scroll-timeline/issues/146#issuecomment-1698159183 for more details.
Fixes #146.
=> Workaround for Safari’s BFCache not playing nice with the polyfill

README.md
If you copy the CSS example in the readme, the `translateY` contains 2 quotes. Therefore, this isn't valid CSS and the example doesn't work out of the box. Removing the quotes resolves to a valid example.
=> Update CSS example in readme

src/scroll-timeline-base.js, src/utils.js
Merging #140 introduced a regression making https://flackr.github.io/scroll-timeline/demo/view-timeline/ no longer work. Upon updating the axis, it always remained `block` (the default value). This is because the `this.axis` was directly manipulated, instead of storing it in the options.
Furthermore, the setter – which validates the axis – didn’t get called in the constructor, so we need to explicitly validate the axis in the constructor as well.
This PR fixes all that.
=> Validate `axis` in constructor + fix axis update regression

src/scroll-timeline-css-parser.js
While debugging something for #153, I noticed that `saveInRelationList` was being called once per ruleset – even though only 1 of the processed ruleset in my test had animation-related properties declared.
This PR adds a quick perf win by bailing out early from the `handleScrollTimelineProps` method in case no animation-related properties have been extracted.
=> Stop processing ScrollTimeline props if no animation-related properties have been declared

demo/view-timeline/index.html, src/scroll-timeline-base.js
This PR fixes https://github.com/flackr/scroll-timeline/issues/165
The polyfill used clientWidth/Height to calculate the size of the principal box of the subject, but clientWidth/Height does not include borders. This caused errors when calculating ranges.
=> Account for subject borders

demo/view-timeline/index.html, src/proxy-animation.js, src/scroll-timeline-base.js
When the source element is resized, the specified timing is outdated and needs to be renormalized. 
This PR solves this by using a ResizeObserver to observe the source element, and trigger a renormalization whenever the size has changed.
=> Renormalize timing on source resize

src/proxy-animation.js, src/scroll-timeline-base.js
Currently each timeline sets up its own scroll listener and resize observer on the source element. As a result we sample scroll position and update animations for each timeline, potentially causing relayouts. (As reported in #46).
This PR registers switches to using only one scroll listener and resize observer per source element, and to sample scroll position only once before updating the timelines and their connected animations.
=> Handle scroll and resize events only once for each scroll source

demo/view-timeline/with-math-value-range.html, src/numeric-values.js, src/proxy-cssom.js, src/scroll-timeline-base.js, src/simplify-calculation.js, src/utils.js
Adding support for CSSMathValues in rangeStart and rangeEnd if they can be simplified to a CSSUnitValue with a `px` unit. 
The following WPT subtests should now pass: 
- View timeline with range as <name> <px> pair.
- View timeline with range as <name> <percent+px> pair.
This is solved by partially implementing [`simplify a calculation tree`](https://www.w3.org/TR/css-values-4/#simplify-a-calculation-tree) and partially implement support for a few more methods ([`type()`](https://drafts.css-houdini.org/css-typed-om/#dom-cssnumericvalue-type), [`to()`](https://drafts.css-houdini.org/css-typed-om/#dom-cssnumericvalue-to) and  [`toSum()`](https://drafts.css-houdini.org/css-typed-om/#dom-cssnumericvalue-tosum)) in the CSSOM/Typed OM proxy.
Note: 
This implementation limited to using CSS Typed …
=> Support CSSMathValue as rangeStart and rangeEnd

src/proxy-cssom.js, src/scroll-timeline-base.js, src/simplify-calculation.js, test/expected.txt
Depends on https://github.com/flackr/scroll-timeline/pull/176
This PR adds support for passing  CSSNumericValues as insets to ViewTimeline. 
```js
new ViewTimeline({
subject: elm,
axis: 'block',
inset: [ CSS.percent(10), CSS.percent(20) ]
})
```
To pass the tests the PR also do the following:
- Adds MutationObserver to observe changes to class attribute on subject.
- Adds getters for startOffset and endOffset read only attributes.
- Adds support for parsing math functions such as calc, through a naive implementation of CSSNumericValue.parse()
This PR does not: 
- add support for relative units such as viewport relative units.
=> Support CSSNumericValues as inset

src/proxy-animation.js, src/scroll-timeline-base.js, test/expected.txt
Adds support for getting and setting `rangeStart` and `rangeEnd` on Animation.
- Adds support for the `'normal'` value
- Adds getters and setters for `rangeStart` and `rangeEnd` 
- setters are limited to ViewTimelines for now, as the existing implementation is limited to ViewTimelines
- Uses CSSNumericValue.parse() to parse string values for range start and range end.
- This adds support for math functions such as calc(100% - 20px).
=> Range attributes

src/scroll-timeline-css.js
In #89 the proxied animations handling got moved around a bit. In #147 (which was merged earlier) a cleanup mechanism for the old `proxyAnimations` was introduced, but this mechanism was not removed in #89. This went unnoticed as it only triggers an error when running in strict mode, as reported in #183.
This PR fixes that.
=> Proxied Animations Cleanup fixup

src/proxy-animation.js
In #178 `parseAnimationRange` was changed to use string values of `"normal"` instead of objects representing the normal range. This essentially broke the parsing of `animation-range`, as later on that function tries to update values in that (now inexistent) object.
On the console, these errors could be seen, as reported in #183:
```
Can’t assign to property "rangeName": not an object
```
This PR fixes this: return the default `"normal"` when no value is given, but continue with the objects when there is a value to parse.
Note that this is only for parsing ranges of `ViewTimelime` instances. For `ScrollTimeline`, more work needs to be done in #153.
_PS: I didn’t get to updating the test results as I’ve got issues launching them with firefox for some reason. Safari works fine, but gives …
=> Only return 'normal' as the range when no value is given.

README.md
While the link in the README did resolve, the URL that’s being promoted is https://scroll-driven-animations.style/
=> Use correct link to SDA minisite

src/proxy-animation.js
I believe this is a regression introduce by #89. When using the polyfill in Safari (which hash a BFCache), one would get errors about trying to read `autoAlignStartTime` from the `details`.
Narrowing things down and working my way up the call tree, the root cause is in `tickAnimation` which tries to get the `details` from the `proxyAnimations`. Since `proxyAnimations` gets cleared on `pagehide`, `details` _can_ be empty, so the whole ticking stop stop if no details are present.
This PR fixes that.
=> Don’t try ticking the animation if there are no details

src/proxy-animation.js
The regex matching animation range names when parsing range offsets eagerly matched `entry` in `entry-crossing`. 
This PR adds a lookahead to fix this issue.
=> Fix bug in animation range name regex

src/proxy-animation.js
Run the auto align start time procedure before checking if animation is ready. 
Currently we run the procedure when ticking animations after adding animations to a timeline or after a scroll or resize event. 
However, this does not update the start time when playing or pausing an existing animation. 
If we don't run the procedure here, tests _can_ time out under some conditions, as the animation will never be ready. This can happen in the [play-animation test](https://github.com/web-platform-tests/wpt/blob/a95a859194890421952a3105e9b69789dbb4c58b/scroll-animations/scroll-timelines/play-animation.html#L130).
No tests should be affected by this PR, but fixing this is a precondition for fixing other issues.
=> Auto align start time before checking if animation is ready

src/proxy-animation.js
Handle case where `effect.updateTiming()` is called with an undefined input.
This happens in the [view-timeline-subject-size-changes test](https://github.com/web-platform-tests/wpt/blob/a95a859194890421952a3105e9b69789dbb4c58b/scroll-animations/view-timelines/view-timeline-subject-size-changes.html#L53).
The PR does not fix the entire test, but it fixes the following error: 
```
promise_test: Unhandled rejection with value: object "TypeError: options is undefined"
```
I will create a separate PR for fixing the test later on.
=> Handle undefined options in updateTimingHandler

src/proxy-animation.js
This is a follow up on #191.
Handle case where effect.updateTiming() is called with an explicit undefined options argument.
This happens in the [view-timeline-subject-size-changes test](https://github.com/web-platform-tests/wpt/blob/a95a859194890421952a3105e9b69789dbb4c58b/scroll-animations/view-timelines/view-timeline-subject-size-changes.html#L53).
After a discussion in #191 we skipped checking for an explicitly undefined options argument, and instead returned if the argumentList was undefined or empty. That does not cover the case where the method is called explicitly with undefined as an argument as below. 
```js
effect.updateTiming(undefined)
// argumentList == [undefined]
// arguementList.length == 1
```
=> Handle explicitly undefined options argument in updateTimingHandler

demo/basic/anonymous-scroll-timeline-animation-shorthand.html, src/scroll-timeline-base.js, src/scroll-timeline-css-parser.js
This PR allows the `self` keyword to be used as the scroller in `scroll()`, e.g. `animation-timeline: scroll(self y);`.
The `anonymous-scroll-timeline-animation-shorthand.html` demo was extended to include this.
No change in WPT results was noticed.
=> Add self keyword for the scroller

src/scroll-timeline-css-parser.js, test/expected.txt
The [progress demo](https://flackr.github.io/scroll-timeline/demo/basic/progress) is currently throwing a "TypeError: Invalid ScrollTimeline Source Type". 
This happens because
1. `parseAnonymousScrollTimeline()` does not set a default source
2. `getAnonymousSourceElement()` requires a source, and will throw an error if one is not set.
Adding 'nearest' as a default anonymous source in `getAnonymousScrollTimelineOptions()`, the same place a default value for `axis` is set. 
https://github.com/flackr/scroll-timeline/blob/db93642a02f0271c2a96a1f15861d04813b67b10/src/scroll-timeline-css-parser.js#L465-L481
https://github.com/flackr/scroll-timeline/blob/db93642a02f0271c2a96a1f15861d04813b67b10/src/scroll-timeline-css-parser.js#L117-L129 …
=> Set default anonymous source to nearest

src/scroll-timeline-base.js
Calls to `updateMeasurements()` schedules a task to update timelines and animations.
`updateMeasurements()` can potentially be called multiple times before the scheduled task is executed. If a task is already scheduled, scheduling new tasks would be redundant.
=> Prevent redundant updates to timelines and animations

src/index.js, src/scroll-timeline-css.js, test/expected.txt
There are may tests that rely on this check before even running the actual tests.
This PR polyfills `CSS.supports(animation-timeline: …)`, thereby allowing more tests to run.
The total number of tests now is 1080 vs 959 before. Checking https://wpt.fyi/results/scroll-animations?label=experimental&label=master&aligned there should be 1117 tests though.
=> Polyfill CSS.supports(animation-timeline: …)

src/scroll-timeline-base.js
We should account for insets when evaluating `targetIsTallerThanContainer`. 
Currently the range is slightly off when the subject is close in size to the inset adjusted scrollport.
=> Account for insets when comparing size of subject to size of scrollport/view progress visibility range

src/proxy-animation.js
I managed to mess up the step numbers in the comments in playInternal. 
This PR adds the correct step numbers in the comments.
=> Fix step numbers in playInternal

test/setup/checkout-wpt.mjs
By shallow cloning and only cloning the master branch, the WPT setup can be sped up, thereby improving the overall speed of the build pipeline.
Without this change – and at the time of writing – 705377 files make up the entire WPT repo and its history. With it, only 89341 files need to be fetched.
See https://www.bram.us/2020/11/11/speed-up-build-times-with-this-little-git-trick/ for details about this trick.
=> Speed up WPT checkout

.github/workflows/gh-pages.yml, test/expected.txt, test/summarize-json.mjs
Having the summary line leads to every PR which alters test expectations conflicting with every other PR which alters them. The summary can be computed by grepping the PASS / FAIL lines anyways so this should reduce the number of merge conflicts to only cases where the same sets of test expectations changed.
=> Remove test summary from test output.

.github/workflows/gh-pages.yml
To run the GitHub actions locally, I use [`nektos/act`](https://github.com/nektos/act).
One of the things `act` can’t do are the GitHub Pages related actions. This PR alters the workflow to skips those steps when `act` is uses, as [per act instructions](https://github.com/nektos/act?tab=readme-ov-file#skipping-steps)
=> Skip GitHub pages steps when using act to build

src/scroll-timeline-base.js, test/expected.txt
Scheduling a task to update timelines, instead of waiting for the next animation frame. 
Some tests only wait for _one_ animation frame. If we wait for the next animation frame before ticking animations, it might result in assertions running right before the animations are ticked.
Tests that that use `waitForNextFrame()` from [web-animations/testcommon.js](https://github.com/web-platform-tests/wpt/blob/a95a859194890421952a3105e9b69789dbb4c58b/web-animations/testcommon.js#L177) such as [the last test in the scroll-animation-inactive-timeline.](https://github.com/web-platform-tests/wpt/blob/a95a859194890421952a3105e9b69789dbb4c58b/scroll-animations/scroll-timelines/scroll-animation-inactive-timeline.html#L137) are affected by this issue.
This test should now pass.
=> Schedule tasks for timeline updates

src/proxy-animation.js, src/scroll-timeline-base.js, src/utils.js
When parsing component values passed as a string to `rangeStart`, `rangeEnd` and `inset` we have previously used str.split(), either with a single whitespace or with a regex with various issues:
- `'calc(2 * 10px) auto'.split(' ')` returns `['calc(2', '*', '10px)', 'auto']`, breaking apart functions
- `'calc(2 * 10px) auto'.split(/(?<!\([^\)]*)\s(?![^\(]*\))/)` returns `['calc(2 * 10px)', 'auto']` as expected, but causes an error in browsers without support for lookahead
This PR adds a utility function `splitIntoComponentValues(input)` that splits a string with multiple component values into an array of individual component value strings. These can then be processed either as keywords or be further parsed using `CSSNumericValue.parse()`.
```js
splitIntoComponentValues('calc(2 * 10px) …
```
=> Add utility function to split string into component values

src/proxy-animation.js
It is currently possible to set values for the attachment range that are valid length-percentage values, but that are not supported in the polyfill yet. 
This will cause en error to be thrown when we try to auto-align the start time, preventing tickAnimation from completing as expected.
We should probably add a stricter validation when setting the range, but for now I think we should catch the exception and fall back to using the full animation range.
Merging this PR should prevent the timeouts that occurred in the WPT subtests in #153
=> Handle exceptions when auto-aligning start time

src/proxy-animation.js
It seems like animation.play() is returning early when running on a finite timeline with the auto-align start time procedure. 
We have implemented a way around the issue, but I finally managed to file a w3c issue: https://github.com/w3c/csswg-drafts/issues/9871.
Adding a todo comment to remind us to update the code once the issue is resolved.
=> Add todo to update code once auto-align issue is answered or closed

demo/view-timeline/index.html
This PR expands the view-timeline demo with an “add insets” option. When enabled, helper lines to indicate where the insets are get drawn on screen.
=> Add inset option to view-timeline demo

src/numeric-values.js, src/proxy-cssom.js, src/simplify-calculation.js, src/tokenizer.js, test/expected.txt
Add proper tokenization and parsing for CSSNumericValue.parse().
=> Implement CSSNumericValue.parse()

src/proxy-cssom.js
=> Handle CSSNumericValue instances while parsing

src/scroll-timeline-base.js
Using `simplifyCalculation()` in `resolvePx()` to resolve CSSMathValues and CSSUnitValues according to spec.
Swithcing to using `resolvePx()` elsewhere, in stead of calling `simplicyCalculation()` directly. 
This gives us one unified code path to resolving px values from CSSNumericValues. 
`resolvePx()` now takes an info/context object that `simplifyCalculation()` can use to resolve relative units. Ritght now it supports `percentageReference` and `fontSize`, but can be extended with values so that we can resolve all relative units, such as viewport units.
The context object is now called `info` but could benefit from a more descriptive name. Suggestions are welcome :)
=> Use simplicyCalculation to resolve px

src/scroll-timeline-base.js, test/expected.txt
By accounting for the clientWidth/height we should pass two of the WAAPI tests in scroll-timeline-range.html.
=> Account for client width and height when calculating scroll distance

src/proxy-animation.js, src/scroll-timeline-base.js, test/expected.txt
Schedule a micro task for `updatingInternal()` after adding an animation. If `updateInternal()` runs in the same task then `animation.currentTime` will be set by the time animation.play() returns.
Delaying this function revealed two other issues that needed to be fixed: 
- Infinite durations needed to be validated in getTimingHandler.
- holdTime was set to unresolved in tickAnimation, flipping the playState from 'finished' to 'running'.
=> Fix scroll-animation.html start and current time subtests

src/proxy-animation.js, test/expected.txt
We should return the string "normal" for rangeStart and rangeEnd (when specified as normal), and not a TimelineRangeOffset. 
This change makes `view-timeline-get-set-range.html` pass again, given that it is run on an uncompressed build (https://github.com/flackr/scroll-timeline/pull/200)  and that we have a proper implementation of CSSNumericValue.parse() (https://github.com/flackr/scroll-timeline/pull/206).
=> Return "normal" for get rangeStart and rangeEnd

src/proxy-animation.js
Fix regression due to https://github.com/flackr/scroll-timeline/pull/223
We should return `normal` as the default  range start and end, but the parsing still expects a TimelineRangeOffset which can cause an issue.
Fixing the issue by only returning `normal` when no range was set by the user, keeping the TimelineRangeOffset from getNormalStart/EndRange otherwise.
There's already a todo to handle the full syntax later.
=> Fix regression due to handling of normal range

src/scroll-timeline-base.js, test/expected.txt
Fixing /scroll-animations/scroll-timelines/current-time-nan.html
=> Return unresolved current time for unattached source

src/proxy-animation.js
Super small bugfixes. I was trying to run the example on the README in my npm'ish branch and there's some other issues (ie: divide by zero exception), but I couldn't see those as the `console.warn` didn't have the error in scope. This PR just adds `catch (e)` to 2 places so we can do `console.warn('<message>', e)`.
=> Print out error when failing to calculate the rangeStart and rangeEnd

.github/workflows/gh-pages.yml
I feel it makes sense to track waapi and css tests separately in the summary. We might want to deliver a lighter bundle without css polyfill. It is also harder to test the css polyfill. Many of the css tests rely on inline styles which we don't support yet.
=> Split summary into css and waapi tests

src/index.js, src/scroll-timeline-css.js
In this implementation, a stylesheet's href is replaced with an object URL to the updated stylesheet href.
=> Parse and transpile external stylesheets - fixes #78.

src/scroll-timeline-css.js
Fixes https://github.com/flackr/scroll-timeline/issues/158.
=> Dont parse stylesheets controlled by aphrodite

README.md
I couldn't figure out why the polyfill wasn't working for me until I checked the actual code of the polyfill and saw that it doesn't work with css from other origins, so I think adding a note explaining this in the readme is pretty important.
Here's [the part of the polyfill](https://github.com/flackr/scroll-timeline/blob/702b716afa35bd2b948a4b208ed552db2472de8e/src/scroll-timeline-css.js#L51) I'm referring to:
```javascript
const url = new URL(linkElement.href, document.baseURI);
if (url.origin !== location.origin) {
// Most likely we won't be able to fetch resources from other origins.
return;
}
```
=> Update README.md with helpful note
